### ISSUE TITLE
Installation: Petunia

### ISSUE THREAD

**Issue by ariutti** [Limulo/website-restyle2016#24]
traduci

**Comment by v1a1l1e1** [comment]
Potevi almeno mettere in allegato l'taliano!

**Comment by ariutti** [comment]
Se per **allegato** intendi il file di testo originale dell'articolo posso consigliarti di visitare o scaricare il repository dell'attuale sito a [questo](https://bitbucket.org/ariutti/limulo.net) indirizzo. 
Ne sei amministratrice.

Tutti gli articoli li trovi in formato **.php** al percorso ```it/templates```. 
Puoi partire da lì, e questo vale per tutti gli altri articoli ancora da tradurre.

**Comment by ariutti** [comment]
Che poi scusa: l'articolo già trasportato in formato **.md** non è forse nella cartella **_post** di questo repo?
Lo trovi sotto il nome ```2011-08-15-petunia.md```
Fammi sapere!

**Comment by v1a1l1e1** [comment]
Certo che non hai un minimo di senso dell'umorismo!
