### ISSUE TITLE
Pagine senza TITOLO

### ISSUE THREAD

**Issue by ariutti** [Limulo/website-restyle2016#8]
se le pagine sono senza titolo:

* da una parte non vengono integrate nella navabar;
* ma dall'altra non compare il titolo nel tab del browser :(
![screenshot from 2016-11-10 10 17 31](https://cloud.githubusercontent.com/assets/6818509/20170941/b343d156-a72e-11e6-95cd-03c46f298df8.png)

Occorre trovare una soluzione alternativa

**Comment by v1a1l1e1** [comment]
1. tutte le pagine hanno il titolo. Un attributo custom tipo 'nav' permette tramite il proprio valore true o false di inserire il titolo nella navbar;
2. si lascia così
3. si trova un modo di agire dinamicamente sull'html risultante

**Comment by v1a1l1e1** [comment]
Soluzione 1 del commento precedente: FUNZIONA
